name: 'Terraform Format'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

defaults:
    run:
      working-directory: ${{ env.tf_actions_working_dir }}
  steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
  
    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      continue-on-error: true

    - name: Add & Commit
      # You may pin to the exact commit or the version.
      # uses: EndBug/add-and-commit@b5dec7ea7647ed6edf307ec828d3aeb6bca69f63
      uses: EndBug/add-and-commit@v5.1.0
      with:
        # Arguments for the git add command
        add: '.'
        # The name of the user that will be displayed as the author of the commit
        author_name: 'Jake Jones'
        # The email of the user that will be displayed as the author of the commit
        author_email: # optional
        # Name of the branch to use, if different from the one that triggered the workflow
        branch: # optional
        # The directory where your repository is located. You should use actions/checkout first to set it up
        cwd: # optional, default is .
        # The message for the commit
        message: 'ran terraform fmt'
        # Arguments for the git rm command
        remove: # optional
        # Whether to use the --signoff option on git commit
        signoff: # optional
        # Arguments for the git tag command (the tag name always needs to be the first word not preceded by a hyphen)
        tag: # optional